### ISSUE TITLE
please visualize it

### ISSUE THREAD

**Issue by huahuayu** [zsais/go-gin-prometheus#32]
hi, the metrics data can be get from http://host/metrics, but it's text, can you please visualize it?

**Comment by Josca** [comment]
Visualize data is not purpose of this library. Metrics on :/metrics endpoint should be scraped with [Prometheus](https://prometheus.io/) service. It also has its own [visualization board](https://prometheus.io/docs/visualization/browser/) for that. But recommended visualization tool is [Grafana](https://prometheus.io/docs/visualization/grafana/) which is standalone visualization service using Prometheus as one of data source.

**Comment by zsais** [comment]
Thanks, @Josca.

@huahuayu Like Josca mentioned, go-gin-prometheus simply collects metrics to be consumed by [Prometheus](https://prometheus.io/). You can visualize with that tool or set up Grafana to pull data from Prometheus to help with visualizations.
